name: yskamto
channels:
  - isuruf/label/tf
  - conda-forge
dependencies:
  - absl-py=0.13.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py38hea4295b_0
  - appnope=0.1.2=py38h10201cd_1
  - argon2-cffi=20.1.0=py38h30f7421_2
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h30f7421_1001
  - c-ares=1.17.1=h27ca646_1
  - ca-certificates=2021.5.30=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2021.5.30=py38h10201cd_0
  - cffi=1.14.5=py38he62ddd7_0
  - chardet=4.0.0=py38h10201cd_1
  - click=8.0.1=py38h10201cd_0
  - cryptography=3.4.7=py38h3c0dae5_0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_1
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h17b34a0_1
  - gast=0.4.0=pyh9f0ad1d_0
  - google-auth=1.30.2=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.38.1=py38h69ee544_0
  - h5py=3.3.0=nompi_py38hb525b2d_100
  - hdf5=1.10.6=nompi_h0fc092c_1114
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.5.0=py38h10201cd_0
  - ipykernel=5.5.5=py38h2cb4d76_0
  - ipython=7.24.1=py38h2cb4d76_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.0=py38h10201cd_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h10201cd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - jupyterthemes=0.20.0=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py38h12a6f45_1
  - krb5=1.19.1=hd92b7a7_0
  - lcms2=2.12=had6a04f_0
  - lerc=2.2.1=h9f76cd9_0
  - lesscpy=0.14.0=pyhd8ed1ab_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcurl=7.77.0=h8fe1914_0
  - libcxx=11.1.0=h168391b_0
  - libdeflate=1.7=h27ca646_5
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.3=h9f76cd9_2
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_22
  - libgfortran5=11.0.1.dev0=hf114ba7_22
  - liblapack=3.9.0=9_openblas
  - libnghttp2=1.43.0=hf3018f0_0
  - libopenblas=0.3.15=openmp_hf330de4_1
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.17.2=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libssh2=1.9.0=hb80f160_6
  - libtiff=4.3.0=hc6122e1_1
  - libwebp-base=1.2.0=h27ca646_2
  - llvm-openmp=11.1.0=hf3c4609_1
  - lz4-c=1.9.3=h9f76cd9_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38hea4295b_0
  - matplotlib=3.3.4=py38h150bfb4_0
  - matplotlib-base=3.3.4=py38ha029820_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py38h30f7421_1003
  - multidict=5.1.0=py38h30f7421_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.1.0=py38h10201cd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h9aa5885_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.2.0=py38h10201cd_0
  - numpy=1.21.0=py38hbf7bb01_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1k=h27ca646_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.2=py38h9b9bf68_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py38h5351710_1
  - pip=21.1.2=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - protobuf=3.17.2=py38h6f2b01f_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h30f7421_2
  - pysocks=1.7.1=py38h10201cd_3
  - python=3.8.10=hf9733c0_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-flatbuffers=2.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=22.1.0=py38h51b17a6_0
  - readline=8.1=hedafd6a_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-learn=0.24.1=py38h397cc00_0
  - scipy=1.6.3=py38hd0c9ec0_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - send2trash=1.7.1=pyhd8ed1ab_0
  - setuptools=49.6.0=py38h10201cd_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h72a2b83_0
  - statsmodels=0.12.2=py38h8369297_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow=2.4.rc0=tensorflow_macos_0.1a1_mlcompute_py38_0
  - tensorflow-addons=0.11.2=tensorflow_macos_0.1a1_mlcompute_py38_0
  - tensorflow-estimator=2.5.0=pyh81a9013_1
  - termcolor=1.1.0=py_2
  - terminado=0.10.1=py38h10201cd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hf7e6567_1
  - tornado=6.1=py38h30f7421_1
  - tqdm=4.57.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typeguard=2.12.1=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38h10201cd_4
  - wrapt=1.12.1=py38h30f7421_3
  - xz=5.2.5=h642e427_1
  - yarl=1.6.3=py38h30f7421_1
  - zeromq=4.3.4=h9f76cd9_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h31e879b_1009
  - zstd=1.5.0=h861e0a7_0
  - pip:
    - cloudpickle==1.6.0
    - docker-pycreds==0.4.0
    - et-xmlfile==1.0.1
    - ffmpeg==1.4
    - gitdb==4.0.9
    - gitpython==3.1.27
    - gym==0.18.3
    - iniconfig==1.1.1
    - ipytest==0.9.1
    - janome==0.4.1
    - jsanimation==0.1
    - mctspy==0.1.1
    - networkx==2.5.1
    - openpyxl==3.0.7
    - pathtools==0.1.2
    - pluggy==0.13.1
    - promise==2.3
    - psutil==5.9.0
    - py==1.10.0
    - pyglet==1.5.15
    - pytest==6.2.3
    - pyyaml==6.0
    - sentry-sdk==1.5.10
    - setproctitle==1.2.3
    - shortuuid==1.0.8
    - smmap==5.0.0
    - toml==0.10.2
    - torch==1.9.0
    - wandb==0.12.15
    - xlrd==2.0.1
prefix: /Users/yskamto/miniforge3/envs/yskamto
