wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1652270631
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      4: 3.8.10
      5: 0.12.15
      8:
      - 4
      - 5
      10:
      - 3
